# Generated by Django 5.2.8 on 2025-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_comment_image_comment_likes_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_whatsapp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file_product',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='user@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.URLField(blank=True, help_text='Link GDrive/Mediafire', max_length=500, null=True),
        ),
    ]
